### ISSUE TITLE
Where's the envelope for the examples?

### ISSUE THREAD

**Issue by devinbost** [googleapis/google-cloudevents#396]
The JSON Schema examples of the events on the main page (https://github.com/googleapis/google-cloudevents) are great! However, they're listed on the page as examples of the CloudEvents specification.
The CloudEvents specification mentions these required properties:

- id: String
- source: URI-reference
- specversion: String
- type: String

However, I don't see any of these envelope properties mentioned in any of the examples listed on the page. 
It looks like the JSON examples (such as [this one](https://googleapis.github.io/google-cloudevents/jsonschema/google/events/cloud/audit/v1/LogEntryData.json)) conform to the JSON Schema specification (draft-04 anyway), but where are the envelopes?

**Comment by jskeet** [comment]
The examples are examples of the payload of the CloudEvents. Eventarc (currently, at least) delivers CloudEvents in *binary mode*, which means the CloudEvent attributes are provided as HTTP headers (ce-id, ce-type etc), not in the body.

**Comment by muncus** [comment]
Devin - I've updated the Readme in line with Jon's comments, to note that the examples contain only the Data portion of the full CloudEvent.

Our goal here is to describe the payload once extracted from the envelope. A json schema (for example) could not specify details about the data payload because the envelope stores it as a simple string (or bytes in the case of a proto-encoded data payload).

Does that address your question? If not, please reopen the issue. Thanks!
